### ISSUE TITLE
Import SHOM tide related data

### ISSUE THREAD

**Issue by yvanlebras** [kimlai/oceanhackathon#1]
No real open data webservice, only "vignette" import OR flat files per harbour..... It would be nice to consider using a real webservice as this is under [opendata mention](http://www.shom.fr/les-services-en-ligne/portail-datashomfr/)

**Comment by kimlai** [comment]
Done in https://github.com/kimlai/oceanhackathon/commit/3d7cee61b1261ac13712622f4c7d08b5ce084e55

**Comment by yvanlebras** [comment]
Great!
